### ISSUE TITLE
`tryResolve` should allow paths with extensions

### ISSUE THREAD

**Issue by OliverJAsh** [dividab/tsconfig-paths#11]
\`tryResolve\` works by appending all possible extensions to the input path. However, in Node `require` paths may already contain the extension. This is sometimes desirable, and tsconfig-paths should work with paths that do and don't contain extensions.

For context, we specify the extension for CSS files, but not for JS files.

**Comment by OliverJAsh** [comment]
I tried adding this to \`tryResolve\`:

``` js
    if (fileExists(physicalPath)) {
      return physicalPath;
    }
```

It gets further with this, however it needs additional work to eliminate paths that are directories, otherwise we get false positives.

**Comment by Jontem** [comment]
Could you give the latest version a try? I made some changes to make tryResolve work more like node's require.resolve. If i understood you correctly it adress your issue

**Comment by Jontem** [comment]
Closing. Please feel free to open the issue if it still exists
