### ISSUE TITLE
Does not support the use of ts-node@^8.0.0

### ISSUE THREAD

**Issue by MarxZhou** [dividab/tsconfig-paths#118]
The current package can only run on ts-node@^7.0.0. Please do a compatible treatment.
I am used to installing ts-node tool packages globally. Now I have to install ts-node@^7.0.0 separately in the local project.
thank you very much!

**Comment by cspotcode** [comment]
Please provide more information.  You're seeing an error message, or some other evidence that it's failing?

**Comment by MarxZhou** [comment]
I tried it again today and found that in the ts-node@^8.10.2 version, the function is normal.
When it failed to run normally before, it always prompted that the path alias could not be resolved.
I remember that ts-node should be version 8.0.* at that time.

The following is the error message in version 8.0.*:

-----------------------------
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'arg'
Require stack:
- D:\study_data\merge_m3u8\node_modules\ts-node\dist\bin.js
---------------------------

![image](https://user-images.githubusercontent.com/39861054/88813484-8eb57d80-d1eb-11ea-8359-c80a39358daa.png)
