### ISSUE TITLE
yarn@berry compatible

### ISSUE THREAD

**Issue by igorkamyshev** [dividab/tsconfig-paths#121]
Hello! I tried to use your great library with yarn@berry and got some error:

```
Error: Your application tried to access ..., but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

I guess, it happened because we must not monkey-patch `require` in yarn@berry. Do you have any idea, how we can fix it? =)

**Comment by igorkamyshev** [comment]
Okay, I create a simple library, it compiles TypeScript and replaces all absolute imports by relative.

https://github.com/solid-soda/tsn

If, someone want to use absolute imports with yarn@berry — I guess, you can try my lib =)

**Comment by cspotcode** [comment]
@igorkamyshev you removed important information from the error that you pasted.  Why?  Is it a secret?

**Comment by igorkamyshev** [comment]
Nope, it is not. I provide full error string.

**Comment by cspotcode** [comment]
The error has an ellipsis in it?  `Error: Your application tried to access ...,`?  Usually this yarn error mentions the name of a library instead of an ellipsis.

**Comment by igorkamyshev** [comment]
Sure, I miss word "will", sorry =D

 I **will** provide full error string.
