### ISSUE TITLE
How to ignore expecific paths?

### ISSUE THREAD

**Issue by lindomar-oliveira** [dividab/tsconfig-paths#126]
```json
    ...
    "paths": {
      "@common/*": ["src/common/*"],
      "@config": ["src/config"],
      "@modules/*": ["(src/*)(?!@common|@config"]
    }
```

Tried the example above but it didn't work.

**I want @modules to list all folders in src, except in common and config.**

**Comment by cspotcode** [comment]
If TypeScript can't do it, then we won't support it either.  You should be able to find answers in the TypeScript Discord, StackOverflow, etc.
https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
