### ISSUE TITLE
Does not work for path mapping starting with `/`

### ISSUE THREAD

**Issue by ashubham** [dividab/tsconfig-paths#128]
I have tsconfig paths configured as:
```json
"paths": {
      "/@utils/*": ["src/utils/*"],
      "/@services/*": ["src/services/*"],
      "/@contexts/*": ["src/contexts/*"],
      "/@translations/": ["src/services/system/localization/translations/index"]
},
```

These fail to resolve to the correct paths due to this line in code: 
https://github.com/dividab/tsconfig-paths/blob/master/src/try-path.ts#L27

Do we need this check ?

**Comment by amonks** [comment]
@ashubham I appreciate your work in finding this!

I'm trying to find a path-mapping solution that works with both parcel and tsconfig-paths, and parcel only likes path replacements when they start with `/`. Removing the line you pointed out met my needs!

**Comment by cspotcode** [comment]
@ashubham can you give me an example of some of the `import` statements you're writing to go along with this `paths` configuration?

**Comment by ashubham** [comment]
I am trying to use https://github.com/vitejs/vite to build/bundle our application. Which needs custom path mappings to start with a `/` to differentiate from the npm namespace `@namespace/package` kind of dependencies.

So my imports look like:

```js
import { getUtilFn } from '/@utils/layout';
import { useQuery } from '/@services/query';
```

**Comment by 0x80** [comment]
@ashubham Just curious, and it's a matter of taste probably, but why do you start with `/@utils` and not just `/utils`? I'm using the latter, and I like the analogy of `/` as "root of your system" where it just points to the `src` folder in my repo. 

As a workaround, until `/` is supported, I'm using `~/` which is like your user "home" folder on OSX so that's very similar :)

**Comment by surgicaI** [comment]
Now that [typescript](https://github.com/microsoft/TypeScript/pull/27980) also allow the paths to start with a `/`, I believe the solution suggested by @ashubham is correct. 
Should I create a pull request for the same

**Comment by benevbright** [comment]
Removing that line did the trick. 

My tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dest",
    "baseUrl": "./",
    "paths": {
      "/opt/*": ["./src/aws-layers/*"]
    }
  },
```
import phrase
```
import { XXXX } from '/opt/utils';
```

Can we fix it?

**Comment by qmg-akara** [comment]
Hello, is there any update on this?

Our use case:
We have a Lambda mono-repo project. We import our lambda layer code as `/opt/nodejs` (this is where AWS Lambda puts our layer code) but as you know this is not available locally so we have `paths: { "/opt/nodejs/*": "packages/layer/src/*" }` in `tsconfig` file. But [this bug causes linting issues](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/86) so we temporarily disabled `import/no-unresolved` which is not great.

Thanks for the great work!

**Comment by qbasic16** [comment]
> Hello, is there any update on this?
> 
> Our use case: We have a Lambda mono-repo project. We import our lambda layer code as `/opt/nodejs` (this is where AWS Lambda puts our layer code) but as you know this is not available locally so we have `paths: { "/opt/nodejs/*": "packages/layer/src/*" }` in `tsconfig` file. But [this bug causes linting issues](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/86) so we temporarily disabled `import/no-unresolved` which is not great.
> 
> Thanks for the great work!

I'm pretty sure a module import starting with an '/' is caused by this line: https://github.com/dividab/tsconfig-paths/blob/master/src/try-path.ts#L27

**Comment by khalidKhaliqi** [comment]
running to the same issue as @qmg-akara, does anyone have a workaround besides forking the repo? 
I have the same issue as this while using T + lambda and trying to share code via lambda layers and locally i like to the /opt/nodejs/* to resolve to relative path.
