### ISSUE TITLE
tsconfig-paths crashes when `compilerOptions` is not present

### ISSUE THREAD

**Issue by wh4everest** [dividab/tsconfig-paths#17]
To reproduce:

tsconfig.json:

```json
{
  "extends": "../../tsconfig.json",
}
```
Now I run: `"test": "mocha --no-timeouts --compilers ts:ts-node/register -r tsconfig-paths/register 'tests/index.ts'"`

And get:

```
/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/lib/tsconfig-loader.js:17
        baseUrl: loadResult.config.compilerOptions.baseUrl,
                                                  ^
TypeError: Cannot read property 'baseUrl' of undefined
    at loadSyncDefault (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/lib/tsconfig-loader.js:17:51)
    at tsConfigLoader (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/lib/tsconfig-loader.js:8:22)
    at Object.configLoader (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/lib/config-loader.js:18:22)
    at Object.register (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/lib/register.js:9:46)
    at Object.<anonymous> (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/tsconfig-paths/register.js:1:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /home/whoeverest/freelance/99abcproj/my-work-project/node_modules/mocha/bin/_mocha:345:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/whoeverest/freelance/99abcproj/my-work-project/node_modules/mocha/bin/_mocha:344:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

If I add `compilerOptions` to `tsconfig.json` it works. This doesn't crash:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "./build"
  }
}
```

Then I get a warning: `Missing baseUrl in compilerOptions. tsconfig-paths will be skipped`

I'm not very familiar with this tool, but it's obvious that it tries to read from `compilerOptions` which in this case is `undefined`. Hope it makes sense.

---

EDIT: BTW, there is a `baseUrl` defined in the top-level `tsconfig.json` which the local one extends. Is that a bug, too?

**Comment by Jontem** [comment]
You need to set the `baseUrl` property of `compilerOptions` because the typescript compiler uses it to resolve `paths` relative to the `baseUrl`

From the [typescript documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html)

> Please notice that "paths" are resolved relative to "baseUrl".

You can't even compile with `tsc` if you have set `paths` without defining `baseUrl`

**Comment by wh4everest** [comment]
I have set `paths` and `baseUrl` in the main `tsconfig.json` from which I extend:

```
{
  "compilerOptions": {
    "sourceMap": true,
    "sourceRoot": ".",
    "...": "...",
    "baseUrl": "./",
    "paths": {
      "*": ["packages/*/src"]
    },
    "plugins": ["..."]
}
```

I think some part of the library code parses the derived `tsconfig.json`, assumes that `compilerOptions` is present on the object (when trying to check if baseUrl is present) and throws the exception "Cannot read property 'baseUrl' of undefined".

**Comment by wh4everest** [comment]
Looking at the source, I don't think `extends` is supported.

**Comment by wh4everest** [comment]
I think this is the issue: https://github.com/TypeStrong/tsconfig/issues/21

**Comment by Jontem** [comment]
Sorry for the quick assumption. I'll have a look how we could solve this.

**Comment by jonaskello** [comment]
Yes, we are using the tsconfig package to read the tsconfig.json file. The tsconfig.json file is not 100% json. For example it allows for comments which the json standard does not. I think submitting a PR for the issue mentioned above would be the best solution.

**Comment by Jontem** [comment]
Please give the latest version a try!

**Comment by lednhatkhanh** [comment]
Still has the same issue: `Missing baseUrl in compilerOptions. tsconfig-paths will be skipped`
My tsconfig.json
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"sourceMap": true,
		"lib": ["esnext"],
		"outDir": "build",
		"rootDir": "src",
		"baseUrl": "",
		"paths": {
			"src": ["./src"]
		},
		"importHelpers": true,
		"noEmitOnError": true,
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"moduleResolution": "node",
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true
	}
}
```

Command: `ts-node --project . -r tsconfig-paths/register ./src/index.ts`
"tsconfig-paths": "^2.6.0"
"ts-node": "3.3.0"

**Comment by Jontem** [comment]
Your'e baseUrl is empty in the example above? Try setting it to `./`

**Comment by lednhatkhanh** [comment]
TS, it works now

**Comment by jonaskello** [comment]
If tsc accepts a blank string and treats it as "./" then maybe we should too?

**Comment by Jontem** [comment]
Yes it looks like it works. But can't find any documentation that this it is supposed to work this way. But should be an easy fix
