### ISSUE TITLE
General guidance on using tsconfig-paths for absolute paths

### ISSUE THREAD

**Issue by matthewharwood** [dividab/tsconfig-paths#19]
I have a small module that has a reference to an absolute path and a namespace called `@morningharwood`.

_This namespace is being defined in my tsconfig._

**morningharwood/tsconfig.json:**

```
"paths": {
  "@morningharwood/*": [
    "libs/*"
  ]
}
```

_This namespace is getting referenced in my entry point to my module named main._

**morningharwood/libs/prerender/src/main.ts:**

```
import { bootstrap } from '@morningharwood/prerender/src/server';
import { SERVER_PORT } from '@morningharwood/prerender/src/server-port';
import { logo } from '@morningharwood/prerender/src/logo';


bootstrap(SERVER_PORT)
  .then(() => console.log(logo(SERVER_PORT)));
```

When I run

`$ node_modules/.bin/ts-node libs/prerender/src/main.ts --port 5000`

I get the error:
`Error: cannot find libs/prerender/src/main.ts --port 5000`

If I run the suggest snippet from your readme the error is now:

```
$ node_modules/.bin/ts-node -r tsconfig-path/register libs/prerender/src/main.ts --port 5000
Error: Cannot find module 'tsconfig-path/register'
```

**Question:**

**Am I doing something stupid with -r flag value?
or is this package not even for absolute paths? Any help?**

**Comment by awinogrodzki** [comment]
You specified tsconfig-path/register, but it's tsconfig-path**s**/register

**Comment by matthewharwood** [comment]
It was 4am in the morning lol thanks for the help!
