### ISSUE TITLE
Version `4.1.2` no longer has the `latest` tag, since `3.14.2` was released

### ISSUE THREAD

**Issue by jdpowell1** [dividab/tsconfig-paths#242]
The `latest` tag needs to be moved back to `4.1.2` so it is reported correctly on npm.

https://www.npmjs.com/package/tsconfig-paths?activeTab=versions

**Comment by Paul75** [comment]
tha tmeans the last version is 3.14.2 ?

**Comment by jonaskello** [comment]
4.1.2 is the latest version. I have reset the tag now but it does not seem to be updated at npmjs.org yet. However the npm command says it is updated so I'll go ahead and close this. Feel free to re-open if it does not work.
