### ISSUE TITLE
Paths in production

### ISSUE THREAD

**Issue by hernique33comiitei** [dividab/tsconfig-paths#257]
A while ago, I saw a post in this issue talking about building with tsconfig-paths. For me it worked like this:
`node -r ts-node/register -r tsconfig-paths/register dist/index.js`
Is it correct for this to remain in production? Or should it somehow stick to the raw path when compiling?

**Comment by marcj** [comment]
You don't need `ts-node/register` when using the build/compiled files in dist/*.js. You only need tsconfig-paths/register. Yes, also in production

**Comment by hernique33comiitei** [comment]
Understood, thanks friend
