### ISSUE TITLE
cannot find module error

### ISSUE THREAD

**Issue by zpbc007** [dividab/tsconfig-paths#28]
this is my tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "commonjs",
    "target": "es6",
    "lib": ["es6"],
    "sourceMap": true,
    "allowJs": true,
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "baseUrl": "./",          
    "paths": {
        "@routes/*": ["src/routes/*"],
        "@src/*": ["src/*"],
        "@middleware/*": ["src/middleware/*"]
    },
    "allowSyntheticDefaultImports": true   
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
      "src/**/*"
  ]
}
```
this is the code in  tsc emited file server.js
```
const config_1 = require("./config");
const index_1 = require("@routes/index");
```
when i run  node -r tsconfig-paths/register ./dist/config/server.js
node throw an error 
```
Error: Cannot find module '@routes/index'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._resolveFilename (/Users/zhaopeng/Documents/code/blind-write/server/node_modules/tsconfig-paths/lib/register.js:31:40)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhaopeng/Documents/code/blind-write/server/dist/config/server.js:6:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

why should that happend?
how can i fix that ?
Thanks a lot

**Comment by jonaskello** [comment]
Tried to make a repro [here](https://github.com/jonaskello/repro-tsconfig-paths-28) but it works.

**Comment by zpbc007** [comment]
Thanks, i think i found what is wrong.
In tsconfig.json i specified outDir as 'dist',  then i run  
```
node -r tsconfig-paths/register ./dist/config/server.js 
```
but the code temped to replace @routes/* with src/routes/* not the dist/routes

So if i comment the outDir option the code will run success.

**Comment by zpbc007** [comment]
![image](https://user-images.githubusercontent.com/20379810/35034025-c284db78-fba7-11e7-98a9-87cd67a92289.png)

**Comment by zpbc007** [comment]
How can i use your plugin and also can use the outDir option

**Comment by jonaskello** [comment]
Could you make a PR to the reproduction repo and add outdir to tsconfig so it will cause the error? Or if you have a fork of the reproduction that I can look at which has the error. it is easier for me to check if I have a small repo which causes the error.

**Comment by zpbc007** [comment]
This is the repo https://github.com/zpbc007/tsconfig

**Comment by jonaskello** [comment]
I see what's going on now. You cannot reference the .ts files when you start from a .js file. I've made a [PR with a fix](https://github.com/zpbc007/tsconfig/pull/1). Basically you need to copy the tsconfig.json over and mirror the structure.

**Comment by zpbc007** [comment]
Thanks a lot for you spending time to help me. It's really helped me. ヽ(○^㉨^)ﾉ♪
