### ISSUE TITLE
Problem when using a custom configFile name

### ISSUE THREAD

**Issue by andrewhathaway** [dividab/tsconfig-paths#31]
Using `tsconfig-paths-webpack-plugin`, when setting the `configFile` option, it seems to go missing and doesn't work. I'm submitting the issue here, as after having a look, there's something strange going on internally to this package. 

When passing the configFile option, the `cwd` variable gets set to the configFile's value that I passed through. At the line in the link, it's the options value: https://github.com/dividab/tsconfig-paths/blob/master/src/tsconfig-loader.ts#L39

However, after running the `resolveConfigPath` it's completely lost and becomes the standard absolute path for `tsconfig.json`, not `tsconfig.production.json` in my case.

I can also confirm that the `TS_NODE_PROJECT` env var is undefined, and won't run the codepath for `if (filename) ...`.

Essentially it seems that even though the `configFile` option is passed through to this package, it doesn't actually care for it and throws it out later on.

**Comment by jonaskello** [comment]
@jontem Do you have an idea of what could be the issue?

**Comment by amodm** [comment]
tsconfig-paths-webpack-plugin accepts a parameter called configFile, [which is supposed to be the path to any custom tsconfig.json file](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin).

[As you can see here](https://github.com/dividab/tsconfig-paths-webpack-plugin/blob/c7c2fd2234fc755419b5375561c3afb0e8a6bfeb/src/plugin.ts#L150), this parameter is passed to TsConfigPaths.loadConfig, even though the definition of loadConfig [takes in only a cwd parameter](https://github.com/dividab/tsconfig-paths/blob/a6babc26bbd4f85bb62828bfb2925807ab081500/src/config-loader.ts#L36)

Further down the call stack, [in tsconfig-loader.ts](https://github.com/dividab/tsconfig-paths/blob/a6babc26bbd4f85bb62828bfb2925807ab081500/src/tsconfig-loader.ts#L43), this leads to the cwd parameter being the path to tsconfig, while filename being undefined, which leads to a directory walk searching for tsconfig.json, which in turn leads to this issue.

**Comment by jonaskello** [comment]
@andrewhathaway I released tsconfig-paths-webpack-plugin 3.0.3 which will hopefully fix this.

**Comment by andrewhathaway** [comment]
Ahh great stuff, thanks all involved! I was just about to prepare a minimal repro!
