### ISSUE TITLE
inherits is not a function

### ISSUE THREAD

**Issue by dlipovac012** [dividab/tsconfig-paths#33]
Hello,
I tried to install and use this module in application I'm working on, but I got this issue 
<img width="852" alt="screen shot 2018-04-05 at 1 24 44 pm" src="https://user-images.githubusercontent.com/11486366/38363514-3e94f260-38d5-11e8-9d45-8125deba0e2f.png">

and when i looked to see whats going on with `busboy` package, this is what I got back:
<img width="420" alt="screen shot 2018-04-05 at 1 29 27 pm" src="https://user-images.githubusercontent.com/11486366/38363567-6bacb058-38d5-11e8-8953-29ddcfdb8770.png">

Also, I'm starting the application with this command: `node --inspect=0.0.0.0:9221 -r tsconfig-paths/register ./index`. Running the app without `-r tsconfig-paths/register` doesnt throw an error at all. Funny thing with all this is that it runs perfectly smooth in one project and it throws this error in another one (this one) and they very much look alike.
Any help and advice is welcome. 🙂 

If it helps:
Its nest.js application (framework based on express)

**Comment by jonaskello** [comment]
I'm not sure what is happening here. To understand what is going on a minimal reproduction would be very helpful.

**Comment by dlipovac012** [comment]
@jonaskello That's a thing: I cant really reproduce this thing since I dont really know what is causing it to fail. I have 2 projects and both of them are using `tsconfig-paths` lib. But they differ in other packages and for one of them relative paths are working, but not for the other. My guess is that some dependency is causing the conflict, but im not sure which one. I can provide a list of installed dependencies for both projects, so you maybe have better idea that way 🙂

**Comment by dlipovac012** [comment]
Solved the issue.. 😄

**Comment by keenondrums** [comment]
@dlipovac012  how did you solve it? I think I got a similar error. I try to import promisify from native node's 'utils', but some other module has a dependency on an npm package called 'utils'. tsconfig-paths resolves my import from 'utils' to that package, which does not contain promisify.
