### ISSUE TITLE
tsconfig-paths 3.3.1 seems to be not compatible with ts-node 6.0.3

### ISSUE THREAD

**Issue by macbric** [dividab/tsconfig-paths#41]
**SETUP**
OS: Windows
Usage: ts-node + mocha

Hello,

There seems to be an incompatibility between tsconfig-paths and ts-node 6.0.3.
The defined paths in my tsconfig.development.json are not found during compilation.

The only way I found to solve this problem was to downgrade ts-node to version 5.0.1. Now, it works perfectly without any other changes.

mocha.opts
```
--require ts-node/register --project tsconfig.development.json
--require ts-node/register --require tsconfig-paths/register
--require ts-node/register test/test-suite.ts
```

tsconfig.development.json
```
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "contract/*": [ "src/contract/*Contract.ts" ]
        }
    }
}
```

Thanks

**Comment by Jontem** [comment]
No response so closing this issue for cleanup purposes.
