### ISSUE TITLE
Using the package with jasmine-ts (ts-node)

### ISSUE THREAD

**Issue by Syltty** [dividab/tsconfig-paths#42]
Hi,

I use Typescript files that are transpiled to Javascript in a dist folder (works fine) and Typescript spec files for my unit tests (my problem).
I have a deep directory structure so I use the paths section of tsconfig.json to map my folders to my modules.
I noticed that when I run jasmine-ts to evaluate my spec files, the paths section is not taken into account and thus I get "Error: Cannot find module" error messages.

**I think tsconfig-paths should solve this problem** but I can't figure out what's wrong.

<root>/package.json contains:
```
"test": "jasmine-ts -r tsconfig-paths/register \"tests/**/*.spec.ts\" JASMINE_CONFIG_PATH=./jasmine.json",
```

_root_/tsconfig.json contains
```
    "paths": {
      "*":["src/*"],
      "engines/*": ["src/engines/*"],
      "typings-custom/*": ["typings-custom/*"]
    },    
```

_root_/jasmine.json contains:
```
{
  "spec_dir": "tests",
  "spec_files": [
    "**/*[sS]pec.ts"
  ],
  "helpers": [
    "helpers/**/*.ts"
  ],
  "stopSpecOnExpectationFailure": true,
  "random": true
}
```

_root_/src/engines/engine1.ts contains
```
export default class Engine1 {
[...]
}
```

_root_/tests/unit/specs/engine1.spec.ts contains:
```
import engine1 from "engines/engine1"; //<= Cannot find module
```

works fine when I put the relative but ugly path
```
import engine1 from "../../../src/engines/engine1";
```

**Comment by jonaskello** [comment]
You need to specify a `baseUrl` field in tsconfig.json. From the [docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html):

```
 {
  "compilerOptions": {
    "baseUrl": ".", // This must be specified if "paths" is.
    "paths": {
      "jquery": ["node_modules/jquery/dist/jquery"] // This mapping is relative to "baseUrl"
    }
  }
}
```

**Comment by Syltty** [comment]
Yes I had this "baseUrl" set to "." I just put a snippet of the tsconfig. Should I put the whole content?

**Comment by jonaskello** [comment]
You could just check that the combination of `baseUrl` and `paths` will result into the correct path.

To troubleshoot it might be helpful for you to start with building your tests using `tsc`. If a regular `tsc` of the tests using your tsconfig.json does not work, tsconfig-paths will not work either. In addition you can use  `tsc --traceResolution` to see where modules are being searched for.

If a regular `tsc` works and `tsconfig-paths` does not we can continue troubleshooting.

**Comment by jonaskello** [comment]
I'll close this because of inactivity. Please re-open if you still have the issue.

**Comment by jelling** [comment]
I ran into the same issue and fixed it by using ts-node with jasmine like this:
```
 "test:alloy": "ts-node -r tsconfig-paths/registernode_modules/jasmine/bin/jasmine.js \"services/**/**.service.spec.ts\"",
```
I suspect the issue is with jasmine-ts but don't have time to investigate / think it's probably best not to get too far away from ts-node as it's already an abstraction.
