### ISSUE TITLE
Q: Can I glob paths?

### ISSUE THREAD

**Issue by jas99** [dividab/tsconfig-paths#47]
```
    "paths": {
      "@ent/*": [
        "server/src/entities/**/*"
      ]
    }
```
Above doesn't work, but can I get this globing somehow in my paths.

Thx

**Comment by jonaskello** [comment]
This package follows the rules that the typescript compiler uses for the paths section in tsconfig.json. Those rules do not allow globbing so this is no possible. For more information see the "Path mapping" section  in the [typescript docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html)
