### ISSUE TITLE
Bootstrap and build

### ISSUE THREAD

**Issue by ybrodsky** [dividab/tsconfig-paths#54]
I am using `tsc` and building into `./build`
Now, I noticed in the build files that my references remained to be `require("@services/package/helper")`;

I can use the [bootstrap option](https://github.com/dividab/tsconfig-paths#bootstrap-tsconfig-paths-with-explicit-params), run my index and everything works as expected.

My question is if there's a way to make tsconfig-paths be part of my build. So after I build, instead of having  `require("@services/package/helper")` I have `require("real/path/to/services/package/helper")`; thus avoid having to require the bootstrap when I am starting the app.

Hope my question is clear enough. Thanks.

**Comment by jonaskello** [comment]
The tsconfig-paths package only works at run-time, so it is not possible to use it to affect the build output. So the answer is basically no, it is not possible to do what you describe with this package.

You probably don't need a bootstrap file though, just running `node -r tsconfig-paths/register your_main_file.js` is often enough.

I know there was talk about tsc supporting plugins kind of like babel, and in that case it would probably be possible to develop a tsc plugin that uses the tsconfig-paths package for resolution. But as of now I don't know any such plugin or how to develop it.

**Comment by Nikoms** [comment]
@ybrodsky Did you make something special? Because, i can not make it work with tsc and then "node -r tsconfig-paths/register build/ ..." ?

**Comment by ybrodsky** [comment]
You have to use the boostrap when running straight out of node without typescript. Check the readme, they have an example.

**Comment by ybrodsky** [comment]
To clarify. I created a boostrap as per the example. In sr the end of the file I added a require to my app entry file. So yo start the app after build I do `node tsconfig.boostrap.js`
