### ISSUE TITLE
Using it with ts-node?

### ISSUE THREAD

**Issue by oleersoy** [dividab/tsconfig-paths#87]
Hi,

I'm trying to get `paths` working with this package.  I have the following `tsconfig.json` configuration:
```
    "baseUrl": "./" /* Base directory to resolve non-absolute module names. */,
    "paths": {
      "@fs/*": ["src/*"],
      "@test/*": ["test/*"]
    },
    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true }
    ],

```

I'm confused about the next step.  It says to do this:

> ts-node -r tsconfig-paths/register main.ts

Is `main.ts` the file that the `main` property in `package.json` points to?  For example if I were to use `tsconfig-paths` with this project:

https://github.com/fireflysemantics/validator

What would I run after installing `tsconfig-paths`?

**Comment by deskoh** [comment]
Can try `npx ts-node -r tsconfig-paths/register src/index.ts`.

**Comment by oleersoy** [comment]
OK - Got it - We have to include the plugin each time we run a specific script.  That's fine as I only need it in certain use cases.  Thanks!
