### ISSUE TITLE
Conflicting module names.

### ISSUE THREAD

**Issue by deskoh** [dividab/tsconfig-paths#88]
See [repo](https://github.com/deskoh/tsconfig-paths-issue) here.

There is an import

```ts
import mongoose from 'mongoose';
```

However, the `baseUrl` will cause the `mongoose` to be resolved to the local `mongoose.ts` instead of the `mongoose` package in `node_modules`.

The VS Code editor and language server seems to resolve it fine (e.g. goto definitions works).

Any way for the modules in `node_modules` to take precedence?

**Comment by ajmeyghani** [comment]
How does your `tsconfig.json` look like? You can try explicitly setting your alias paths, for example:

```
    "baseUrl": "./",
    "paths": {
      "*": ["node_modules/*"],
      "@hooks/*": ["src/hooks/*"]
    }

```

**Comment by deskoh** [comment]
Issue seemed to be fixed now.

**Comment by balasan** [comment]
still seeing this issue with `v3.9.0`
in my case it was importing a local `src/queue.js` file instead of the `queue` npm module from node_modules 

adding `"*": ["node_modules/*"],` to paths solved the issue for me but it feels a little hacky
