### ISSUE TITLE
How to use with Jest?

### ISSUE THREAD

**Issue by AhmedMKamal** [dividab/tsconfig-paths#97]
I'm trying to use your package with Jest to test React project but I can't get it to work,
below is my Jest configuration.

```javascript
// jest.config.js
module.exports = {
  // rest of config...
  setupFilesAfterEnv: ['./tests/setup.ts']
};
```

```javascript
// tests/setup.ts
import appRootPath from 'app-root-path';
import tsConfig from '../tsconfig.json';
import tsConfigPaths from 'tsconfig-paths';

let cleanup: () => void;

beforeAll(() => {
  cleanup = tsConfigPaths.register({
    baseUrl: appRootPath.path,
    paths: tsConfig.compilerOptions.paths
  });
});

afterAll(() => {
  cleanup();
});
```

it keeps throwing errors like "Cannot find module '@views/components/error-boundary' from 'App.tsx'"

any ideas on how to use it with Jest, keep in mind that Jest doesn't support the `--require` flag.

**Comment by geersch** [comment]
@AhmedMKamal, you don't need to use that package.

If you use the `baseUrl`and `paths` options in your `tsconfig` file, you must make sure to also configure the `moduleNameMapper` option in your Jest config.

**tsconfig.json**

```ts
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@app/*": ["src/*"]
    }
  }
}
```

**jest config.json**

```json
{ 
  "moduleNameMapper": {
    "^@app/(.*)$": "<rootDir>/$1"
  }
}
```

`ts-jest` provides a helper to transform the mapping from `tsconfig` to Jest config format, but it you use it you need the `.js` version of the config file.

**jest.config.js**

```js
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig');

module.exports = {
  //...
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths /*, { prefix: '<rootDir>/' } */ )
};
```

More information can be found here:

https://kulshekhar.github.io/ts-jest/user/config/

**Comment by AhmedMKamal** [comment]
ok cool, the `pathsToModuleNameMapper` helper worked perfectly, thanks for the hint.

just being curious, the `'<rootDir>/'` prefix seems to be required why did you comment it out?

**Comment by geersch** [comment]
@AhmedMKamal : No reason, updated the sample.

**Comment by aelbore** [comment]
@geersch you can try  to install `alias-hq` here's the docs https://github.com/davestewart/alias-hq/blob/master/docs/integrations.md
